# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
MCU ?= atmega32u4
CONSOLE_ENABLE ?= yes
RGBLIGHT_ENABLE ?= no
ENCODER_ENABLE ?= yes
LTO_ENABLE ?= yes
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
AUDIO_ENABLE ?= no
