/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION ym68
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER YMDK
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN E2
#endif // RGB_DI_PIN

#ifndef RGBLED_NUM
#   define RGBLED_NUM 20
#endif // RGBLED_NUM

#ifndef RGBLIGHT_LIMIT_VAL
#   define RGBLIGHT_LIMIT_VAL 255
#endif // RGBLIGHT_LIMIT_VAL

#ifndef RGBLIGHT_HUE_STEP
#   define RGBLIGHT_HUE_STEP 8
#endif // RGBLIGHT_HUE_STEP

#ifndef RGBLIGHT_SAT_STEP
#   define RGBLIGHT_SAT_STEP 8
#endif // RGBLIGHT_SAT_STEP

#ifndef RGBLIGHT_VAL_STEP
#   define RGBLIGHT_VAL_STEP 8
#endif // RGBLIGHT_VAL_STEP

#ifndef PRODUCT
#   define PRODUCT ym68
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0xD896
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x594D
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 15
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { D0, D1, D2, D3, D5, D4, D6, D7, B4, F7, F6, F5, F4, F1, F0 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B0, B1, B2, B3, B7 }
#endif // MATRIX_ROW_PINS
