# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= atmel-dfu
MCU ?= atmega32u4
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= no
BACKLIGHT_ENABLE ?= yes
RGBLIGHT_ENABLE ?= yes
BLUETOOTH_ENABLE ?= no
AUDIO_ENABLE ?= no
BOOTMAGIC_ENABLE ?= lite
