/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION smol_40/v
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER LeAK
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN F4
#endif // RGB_DI_PIN

#ifndef RGBLED_NUM
#   define RGBLED_NUM 1
#endif // RGBLED_NUM

#ifndef RGBLIGHT_HUE_STEP
#   define RGBLIGHT_HUE_STEP 8
#endif // RGBLIGHT_HUE_STEP

#ifndef RGBLIGHT_SAT_STEP
#   define RGBLIGHT_SAT_STEP 8
#endif // RGBLIGHT_SAT_STEP

#ifndef RGBLIGHT_VAL_STEP
#   define RGBLIGHT_VAL_STEP 8
#endif // RGBLIGHT_VAL_STEP

#ifndef PRODUCT
#   define PRODUCT smol_40/v
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x0015
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x414B
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 12
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { D2, D1, D0, B7, D3, D5, D4, D6, D7, B4, B5, B6 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 4
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { C6, C7, F0, F1 }
#endif // MATRIX_ROW_PINS
