/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION damapad
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER Bolsa Keyboard Supply
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT damapad
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x6470
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x6D64
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 6
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F0, F1, F4, F5, F6, B7 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 3
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { E6, F7, C7 }
#endif // MATRIX_ROW_PINS
