/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0100
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION keebio/iris/rev1
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER Keebio
#endif // MANUFACTURER

#ifndef RGB_DI_PIN
#   define RGB_DI_PIN D3
#endif // RGB_DI_PIN

#ifndef RGBLED_NUM
#   define RGBLED_NUM 12
#endif // RGBLED_NUM

#ifndef PRODUCT
#   define PRODUCT keebio/iris/rev1
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x1256
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0xCB10
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 7
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { D4, C6, D7, E6, B4, B5, B6 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 4
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { B2, B3, B1, F7 }
#endif // MATRIX_ROW_PINS
