# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
MCU ?= atmega32u4
BOOTMAGIC_ENABLE ?= no
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
NKRO_ENABLE ?= no
BACKLIGHT_ENABLE ?= yes
MIDI_ENABLE ?= no
AUDIO_ENABLE ?= no
UNICODE_ENABLE ?= no
BLUETOOTH_ENABLE ?= no
RGBLIGHT_ENABLE ?= yes
SLEEP_LED_ENABLE ?= no
ENCODER_ENABLE ?= yes
