/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DESCRIPTION
#   define DESCRIPTION lagom
#endif // DESCRIPTION

#ifndef PRODUCT
#   define PRODUCT lagom
#endif // PRODUCT