# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
MCU ?= atmega32u4
CONSOLE_ENABLE ?= no
RGBLIGHT_ENABLE ?= yes
ENCODER_ENABLE ?= no
OLED_DRIVER_ENABLE ?= yes
WPM_ENABLE ?= yes
LTO_ENABLE ?= yes
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= yes
COMMAND_ENABLE ?= no
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= yes
AUDIO_ENABLE ?= no
