# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
LAYOUTS ?= ['ortho_5x12']
MCU ?= atmega32u4
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= yes
SLEEP_LED_ENABLE ?= no
NKRO_ENABLE ?= no
BACKLIGHT_ENABLE ?= no
MIDI_ENABLE ?= no
UNICODE_ENABLE ?= no
BLUETOOTH_ENABLE ?= no
AUDIO_ENABLE ?= no
BOOTMAGIC_ENABLE ?= lite
