/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION mac7_pcb
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION COL2ROW
#endif // DIODE_DIRECTION

#ifndef PRODUCT
#   define PRODUCT mac7_pcb
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x0014
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0x414B
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 7
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { E6, B4, B5, B1, B3, B2, B6 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 1
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { D7 }
#endif // MATRIX_ROW_PINS
