# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= atmel-dfu
MCU ?= atmega32u4
BOOTMAGIC_ENABLE ?= yes
MOUSEKEY_ENABLE ?= no
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= no
COMMAND_ENABLE ?= no
NKRO_ENABLE ?= yes
BACKLIGHT_ENABLE ?= no
RGBLIGHT_ENABLE ?= yes
AUDIO_ENABLE ?= no
ENCODER_ENABLE ?= yes
OLED_ENABLE ?= yes
OLED_DRIVER_ENABLE ?= yes
