/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DEBOUNCE
#   define DEBOUNCE 5
#endif // DEBOUNCE

#ifndef DEVICE_VER
#   define DEVICE_VER 0x0001
#endif // DEVICE_VER

#ifndef DESCRIPTION
#   define DESCRIPTION atreus62
#endif // DESCRIPTION

#ifndef DIODE_DIRECTION
#   define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef MANUFACTURER
#   define MANUFACTURER Profet
#endif // MANUFACTURER

#ifndef PRODUCT
#   define PRODUCT atreus62
#endif // PRODUCT

#ifndef PRODUCT_ID
#   define PRODUCT_ID 0x0010
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#   define VENDOR_ID 0xFEED
#endif // VENDOR_ID

#ifndef MATRIX_COLS
#   define MATRIX_COLS 13
#endif // MATRIX_COLS

#ifndef MATRIX_COL_PINS
#   define MATRIX_COL_PINS { F4, F5, F6, F7, B1, B3, B2, B6, B5, B4, E6, D7, C6 }
#endif // MATRIX_COL_PINS


#ifndef MATRIX_ROWS
#   define MATRIX_ROWS 5
#endif // MATRIX_ROWS

#ifndef MATRIX_ROW_PINS
#   define MATRIX_ROW_PINS { D2, D3, D1, D0, D4 }
#endif // MATRIX_ROW_PINS
