# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= caterina
MCU ?= atmega32u4
BOOTMAGIC_ENABLE ?= no
MOUSEKEY_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
CONSOLE_ENABLE ?= yes
COMMAND_ENABLE ?= yes
NKRO_ENABLE ?= no
UNICODE_ENABLE ?= yes
SLEEP_LED_ENABLE ?= no
