/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DESCRIPTION
#   define DESCRIPTION boardsource/equals/60
#endif // DESCRIPTION

#ifndef PRODUCT
#   define PRODUCT boardsource/equals/60
#endif // PRODUCT