/* This file was generated by `qmk generate-config-h`. Do not edit or copy. */

#pragma once

#ifndef DESCRIPTION
#   define DESCRIPTION boardsource/5x12
#endif // DESCRIPTION

#ifndef PRODUCT
#   define PRODUCT boardsource/5x12
#endif // PRODUCT